### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by colindaven** [erasche/docker-galaxy-annotation#6]
Impressive sounding project, will try soon.

One link is broken:
https://github.com/TAMU-CPT/galaxy-webapollo

cheers
Colin

**Comment by colindaven** [comment]
Also the link "Using large external BLAST databases" is missing. This was also detalled nicely in the docker BLAST+ repository.

**Comment by hexylena** [comment]
I'm sorry for the missing documentation. This image has been migrated to a different location, I'm afraid I forgot to mark this as deprecated. https://github.com/galaxy-genome-annotation/docker-galaxy-genome-annotation/
